### ISSUE TITLE
To-Do

### ISSUE THREAD

**Issue by CasAndreu** [norawebbwilliams/cambridge_elements#2]
- [x] Figure out why sometimes `jupyter notebook` asks for a token and other times for a password: it does say in [here](https://github.com/jupyter/notebook/issues/2254) that [setting up a password ](https://jupyter-notebook.readthedocs.io/en/latest/public_server.html) should over-write the token credentials.
- [x] Clean `warnings` that pop up in the modules (e.g. deprecated data transformation function
- [x] Add logos and NSF mentions to slides
- [x] Add a last piece of code in the binary classifiers module showing how to load and use the trained models
